create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.purchase_requests(id) on delete cascade,
  buyer_id uuid not null references auth.users(id) on delete cascade,
  farmer_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  rating smallint not null check (rating between 1 and 5),
  message text,
  created_at timestamptz not null default now()
);

create index if not exists reviews_request_id_idx on public.reviews (request_id);
create index if not exists reviews_farmer_id_idx on public.reviews (farmer_id);
create index if not exists reviews_buyer_id_idx on public.reviews (buyer_id);

alter table public.reviews enable row level security;

create policy if not exists "Authenticated users can read reviews" on public.reviews
  for select
  using (auth.uid() is not null);

create policy if not exists "Buyers can create reviews for their requests" on public.reviews
  for insert
  with check (auth.uid() = buyer_id);
