alter table public.products
  add column if not exists farmer_id uuid references auth.users(id) on delete cascade;

create index if not exists products_farmer_id_idx on public.products (farmer_id);

create table if not exists public.purchase_requests (
  id bigint generated by default as identity primary key,
  product_id integer not null references public.products(id) on delete cascade,
  product_title text not null,
  farmer_id uuid not null references auth.users(id) on delete cascade,
  buyer_id uuid not null references auth.users(id) on delete cascade,
  buyer_email text,
  requested_quantity numeric(12, 2) not null check (requested_quantity > 0),
  message text check (char_length(message) <= 1000),
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'ready', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists purchase_requests_farmer_id_idx on public.purchase_requests (farmer_id, created_at desc);
create index if not exists purchase_requests_buyer_id_idx on public.purchase_requests (buyer_id, created_at desc);

alter table public.purchase_requests enable row level security;

create policy "buyers create their purchase requests"
  on public.purchase_requests for insert to authenticated
  with check (
    auth.uid() = buyer_id
    and farmer_id = (select farmer_id from public.products where id = product_id)
  );

create policy "participants view their purchase requests"
  on public.purchase_requests for select to authenticated
  using (auth.uid() = buyer_id or auth.uid() = farmer_id);

create policy "farmers update their purchase requests"
  on public.purchase_requests for update to authenticated
  using (auth.uid() = farmer_id)
  with check (auth.uid() = farmer_id);