create table if not exists public.consumer_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.consumer_profiles enable row level security;

drop policy if exists "authenticated users can view consumer profiles" on public.consumer_profiles;
create policy "authenticated users can view consumer profiles"
  on public.consumer_profiles for select to authenticated
  using (true);

drop policy if exists "users upsert own consumer profile" on public.consumer_profiles;
create policy "users upsert own consumer profile"
  on public.consumer_profiles for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "users update own consumer profile" on public.consumer_profiles;
create policy "users update own consumer profile"
  on public.consumer_profiles for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

alter table public.farmer_profiles
  add column if not exists avatar_url text;

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_url text not null,
  image_path text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.product_images enable row level security;

drop policy if exists "authenticated users can view product images" on public.product_images;
create policy "authenticated users can view product images"
  on public.product_images for select to authenticated
  using (true);

drop policy if exists "farmers manage own product images" on public.product_images;
create policy "farmers manage own product images"
  on public.product_images for insert to authenticated
  with check (
    exists (
      select 1
      from public.products p
      where p.id = product_id and p.farmer_id = auth.uid()
    )
  );

create policy "farmers update own product images"
  on public.product_images for update to authenticated
  using (
    exists (
      select 1
      from public.products p
      where p.id = product_id and p.farmer_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.products p
      where p.id = product_id and p.farmer_id = auth.uid()
    )
  );

create policy "farmers delete own product images"
  on public.product_images for delete to authenticated
  using (
    exists (
      select 1
      from public.products p
      where p.id = product_id and p.farmer_id = auth.uid()
    )
  );
